name: Quality Assurance

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: go test -v ./...

  lint:
    name: Lint

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --tests=false
